// js/data.js
// 課程單元與題庫資料（翰林版六年級數學課程大綱示意）。

export const UNITS = [
  {
    id: "fraction-multiply",
    title: "分數的乘法",
    semester: "六上",
    icon: "✖️",
    available: true,
    description: "分數乘以整數、分數乘以分數、化簡與帶分數運算。",
  },
  {
    id: "fraction-divide",
    title: "分數的除法",
    semester: "六上",
    icon: "➗",
    available: true,
    description: "分數除以整數、分數除以分數、倒數的應用。",
  },
  {
    id: "ratio",
    title: "比與比值",
    semester: "六上",
    icon: "⚖️",
    available: false,
    description: "認識比、化簡比與比值的應用。",
  },
  {
    id: "circle",
    title: "圓的周長與面積",
    semester: "六上",
    icon: "⭕",
    available: false,
    description: "圓周率、圓周長與圓面積公式應用。",
  },
  {
    id: "solid-shapes",
    title: "角柱與圓柱",
    semester: "六上",
    icon: "🧊",
    available: false,
    description: "認識角柱、圓柱的體積與表面積。",
  },
  {
    id: "statistics",
    title: "統計圖表",
    semester: "六上",
    icon: "📊",
    available: false,
    description: "長條圖、折線圖與圓形圖的判讀與繪製。",
  },
  {
    id: "decimal-divide",
    title: "小數的除法",
    semester: "六下",
    icon: "🔢",
    available: false,
    description: "小數除以小數、商的估算與驗算。",
  },
  {
    id: "proportion",
    title: "比例與正比",
    semester: "六下",
    icon: "📐",
    available: false,
    description: "比例式、正比關係與生活應用問題。",
  },
  {
    id: "percentage",
    title: "百分率與應用",
    semester: "六下",
    icon: "💯",
    available: false,
    description: "百分率、折扣與利率的計算。",
  },
  {
    id: "speed",
    title: "速率",
    semester: "六下",
    icon: "🚗",
    available: false,
    description: "速度、時間、距離三者關係的應用問題。",
  },
];

export function getUnitById(id) {
  return UNITS.find((u) => u.id === id);
}

// 分數的乘法題庫
export const FRACTION_MULTIPLY_QUESTIONS = [
  {
    id: "fm-01",
    type: "choice",
    prompt: "1/2 × 2/3 = ?",
    choices: ["1/3", "2/5", "1/6", "2/3"],
    answer: "1/3",
    hint: "分子相乘、分母相乘，再化簡。",
    explanation: "(1×2)/(2×3) = 2/6 = 1/3",
  },
  {
    id: "fm-02",
    type: "choice",
    prompt: "3/4 × 1/2 = ?",
    choices: ["3/8", "4/6", "1/2", "3/4"],
    answer: "3/8",
    hint: "分子相乘、分母相乘。",
    explanation: "(3×1)/(4×2) = 3/8，已是最簡分數。",
  },
  {
    id: "fm-03",
    type: "input",
    prompt: "2/3 × 3/5 = ?（請輸入最簡分數，如 1/2）",
    answer: "2/5",
    hint: "先相乘再約分：(2×3)/(3×5)。",
    explanation: "(2×3)/(3×5) = 6/15 = 2/5",
  },
  {
    id: "fm-04",
    type: "choice",
    prompt: "2 × 3/4 = ?（整數乘以分數）",
    choices: ["3/2", "6/4", "3又1/2", "1又1/2"],
    answer: "1又1/2",
    hint: "把整數看成 2/1，再與分數相乘，最後化為帶分數。",
    explanation: "2/1 × 3/4 = 6/4 = 3/2 = 1又1/2",
  },
  {
    id: "fm-05",
    type: "input",
    prompt: "1又1/2 × 2/3 = ?（請輸入最簡分數或整數）",
    answer: "1",
    hint: "先把帶分數換成假分數：1又1/2 = 3/2。",
    explanation: "3/2 × 2/3 = 6/6 = 1",
  },
  {
    id: "fm-06",
    type: "choice",
    prompt: "5/6 × 3/10 = ?",
    choices: ["1/4", "15/60", "1/2", "3/6"],
    answer: "1/4",
    hint: "相乘後約分，注意分子分母可先約分再相乘會更快。",
    explanation: "(5×3)/(6×10) = 15/60 = 1/4",
  },
  {
    id: "fm-07",
    type: "input",
    prompt: "4/5 × 5/8 = ?（請輸入最簡分數）",
    answer: "1/2",
    hint: "先觀察分子分母是否可以先約分。",
    explanation: "(4×5)/(5×8) = 20/40 = 1/2",
  },
  {
    id: "fm-08",
    type: "choice",
    prompt: "一杯果汁的 2/3 是柳橙汁，喝掉這杯果汁的 3/4，喝掉的柳橙汁佔全杯的幾分之幾？",
    choices: ["1/2", "5/12", "2/3", "3/4"],
    answer: "1/2",
    hint: "喝掉的柳橙汁 = 2/3 × 3/4。",
    explanation: "2/3 × 3/4 = 6/12 = 1/2",
  },
  {
    id: "fm-09",
    type: "input",
    prompt: "3/7 × 7/9 = ?（請輸入最簡分數）",
    answer: "1/3",
    hint: "分子與分母中有相同因數可以先約分。",
    explanation: "(3×7)/(7×9) = 21/63 = 1/3",
  },
  {
    id: "fm-10",
    type: "choice",
    prompt: "2又1/2 × 2/5 = ?",
    choices: ["1", "1又1/5", "4/5", "1/2"],
    answer: "1",
    hint: "先把帶分數換成假分數：2又1/2 = 5/2。",
    explanation: "5/2 × 2/5 = 10/10 = 1",
  },
];

// 分數的除法題庫
export const FRACTION_DIVIDE_QUESTIONS = [
  {
    id: "fd-01",
    type: "choice",
    prompt: "1/2 ÷ 1/3 = ?",
    choices: ["3/2", "1/6", "2/3", "1/5"],
    answer: "3/2",
    hint: "除以一個分數等於乘以它的倒數。",
    explanation: "1/2 ÷ 1/3 = 1/2 × 3/1 = 3/2",
  },
  {
    id: "fd-02",
    type: "choice",
    prompt: "2/3 ÷ 4/9 = ?",
    choices: ["3/2", "8/27", "2/3", "1/2"],
    answer: "3/2",
    hint: "把除法換成乘以倒數：2/3 × 9/4。",
    explanation: "2/3 × 9/4 = 18/12 = 3/2",
  },
  {
    id: "fd-03",
    type: "input",
    prompt: "3/4 ÷ 3 = ?（整數除法，請輸入最簡分數）",
    answer: "1/4",
    hint: "把整數 3 看成 3/1，再取倒數 1/3 相乘。",
    explanation: "3/4 ÷ 3/1 = 3/4 × 1/3 = 3/12 = 1/4",
  },
  {
    id: "fd-04",
    type: "choice",
    prompt: "5 ÷ 2/3 = ?（整數除以分數）",
    choices: ["7又1/2", "10/3", "3又1/3", "2/15"],
    answer: "7又1/2",
    hint: "5 ÷ 2/3 = 5 × 3/2。",
    explanation: "5/1 × 3/2 = 15/2 = 7又1/2",
  },
  {
    id: "fd-05",
    type: "input",
    prompt: "1又1/2 ÷ 3/4 = ?（請輸入最簡分數或整數）",
    answer: "2",
    hint: "先把帶分數換成假分數：1又1/2 = 3/2。",
    explanation: "3/2 ÷ 3/4 = 3/2 × 4/3 = 12/6 = 2",
  },
  {
    id: "fd-06",
    type: "choice",
    prompt: "7/8 ÷ 7/4 = ?",
    choices: ["1/2", "2", "49/32", "7/32"],
    answer: "1/2",
    hint: "乘以倒數：7/8 × 4/7。",
    explanation: "7/8 × 4/7 = 28/56 = 1/2",
  },
  {
    id: "fd-07",
    type: "input",
    prompt: "2/5 ÷ 4/15 = ?（請輸入最簡分數或整數）",
    answer: "3/2",
    hint: "乘以倒數後再約分。",
    explanation: "2/5 × 15/4 = 30/20 = 3/2",
  },
  {
    id: "fd-08",
    type: "choice",
    prompt: "小明有 3/4 公升的果汁，平分給 3 個人，每人可分到多少公升？",
    choices: ["1/4", "3/12", "9/4", "1/3"],
    answer: "1/4",
    hint: "平分給 3 人就是 3/4 ÷ 3。",
    explanation: "3/4 ÷ 3 = 3/4 × 1/3 = 1/4",
  },
  {
    id: "fd-09",
    type: "input",
    prompt: "5/6 ÷ 5/9 = ?（請輸入最簡分數或整數）",
    answer: "3/2",
    hint: "乘以倒數：5/6 × 9/5。",
    explanation: "5/6 × 9/5 = 45/30 = 3/2",
  },
  {
    id: "fd-10",
    type: "choice",
    prompt: "3又1/3 ÷ 5/6 = ?",
    choices: ["4", "2又1/2", "5/18", "1又2/3"],
    answer: "4",
    hint: "先把帶分數換成假分數：3又1/3 = 10/3。",
    explanation: "10/3 ÷ 5/6 = 10/3 × 6/5 = 60/15 = 4",
  },
];

export const QUESTION_BANKS = {
  "fraction-multiply": FRACTION_MULTIPLY_QUESTIONS,
  "fraction-divide": FRACTION_DIVIDE_QUESTIONS,
};
