export const STATIC_QUESTIONS_UNIT_6_7 = [
  {
    id: "static-u6-s01-q01",
    stageId: "kx-unit6-stage-01",
    unitId: "kx-unit6",
    type: "choice",
    prompt: "一個圓的直徑是 10 公分，圓周長是 31.4 公分。圓周長除以直徑的值是多少？",
    answer: "3.14",
    hint: "用圓周長除以直徑，得到圓周率的近似值。",
    explanation: "31.4 ÷ 10＝3.14，所以這個圓的圓周率近似值是 3.14。",
    concept: "圓周率：圓周長與直徑的比值",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["3.14", "6.28", "31.4", "314"],
  },
  {
    id: "static-u6-s01-q02",
    stageId: "kx-unit6-stage-01",
    unitId: "kx-unit6",
    type: "input",
    prompt: "一個圓的圓周長是 62.8 公分，直徑是 20 公分。圓周長除以直徑是多少？答案只填數字。",
    answer: "3.14",
    hint: "把 62.8 公分平均分成 20 份。",
    explanation: "62.8 ÷ 20＝3.14，所以圓周長除以直徑是 3.14。",
    concept: "圓周率：以圓周長除以直徑",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s01-q03",
    stageId: "kx-unit6-stage-01",
    unitId: "kx-unit6",
    type: "choice",
    prompt: "圓周率用 3.14。一個圓的圓周長是 94.2 公分，直徑是多少公分？",
    answer: "30",
    hint: "直徑＝圓周長÷圓周率。",
    explanation: "94.2 ÷ 3.14＝30，所以直徑是 30 公分。",
    concept: "圓周率：由圓周長反推直徑",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["15", "30", "47.1", "60"],
  },
  {
    id: "static-u6-s01-q04",
    stageId: "kx-unit6-stage-01",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。直徑 8 公分的圓，圓周長是多少公分？答案只填數字。",
    answer: "25.12",
    hint: "圓周長＝圓周率×直徑。",
    explanation: "3.14 × 8＝25.12，所以圓周長是 25.12 公分。",
    concept: "圓周率：用直徑求圓周長",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s01-q05",
    stageId: "kx-unit6-stage-01",
    unitId: "kx-unit6",
    type: "choice",
    prompt: "圓周率用 3.14。半徑 5 公分的圓，下列哪一個敘述正確？",
    answer: "直徑是 10 公分，圓周長是 31.4 公分",
    hint: "先把半徑乘以 2 得到直徑，再求圓周長。",
    explanation: "半徑 5 公分，所以直徑是 10 公分；3.14 × 10＝31.4，圓周長是 31.4 公分。",
    concept: "圓周率：半徑、直徑與圓周長",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: [
      "直徑是 10 公分，圓周長是 31.4 公分",
      "直徑是 5 公分，圓周長是 15.7 公分",
      "直徑是 10 公分，圓周長是 15.7 公分",
      "直徑是 25 公分，圓周長是 78.5 公分",
    ],
  },
  {
    id: "static-u6-s02-q01",
    stageId: "kx-unit6-stage-02",
    unitId: "kx-unit6",
    type: "input",
    prompt: "一個圓的半徑是 12 公分，直徑是多少公分？答案只填數字。",
    answer: "24",
    hint: "直徑是半徑的 2 倍。",
    explanation: "12 × 2＝24，所以直徑是 24 公分。",
    concept: "直徑與半徑：直徑是半徑的兩倍",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s02-q02",
    stageId: "kx-unit6-stage-02",
    unitId: "kx-unit6",
    type: "choice",
    prompt: "一個圓的直徑是 18 公分，半徑是多少公分？",
    answer: "9",
    hint: "半徑是直徑的一半。",
    explanation: "18 ÷ 2＝9，所以半徑是 9 公分。",
    concept: "直徑與半徑：半徑是直徑的一半",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["6", "9", "18", "36"],
  },
  {
    id: "static-u6-s02-q03",
    stageId: "kx-unit6-stage-02",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。一個圓的圓周長是 75.36 公分，半徑是多少公分？答案只填數字。",
    answer: "12",
    hint: "先用圓周長除以 3.14 求直徑，再除以 2。",
    explanation: "75.36 ÷ 3.14＝24，直徑是 24 公分；24 ÷ 2＝12，所以半徑是 12 公分。",
    concept: "直徑與半徑：由圓周長反推半徑",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s02-q04",
    stageId: "kx-unit6-stage-02",
    unitId: "kx-unit6",
    type: "choice",
    prompt: "圓周率用 3.14。下列哪一個圓的半徑是 7 公分，且圓周長是 43.96 公分？",
    answer: "直徑 14 公分的圓",
    hint: "半徑 7 公分時，直徑應是 14 公分。",
    explanation: "半徑 7 公分的直徑是 14 公分；3.14 × 14＝43.96，所以正確的是直徑 14 公分的圓。",
    concept: "直徑與半徑：配合圓周長檢查",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["直徑 7 公分的圓", "直徑 10 公分的圓", "直徑 14 公分的圓", "直徑 21 公分的圓"],
  },
  {
    id: "static-u6-s02-q05",
    stageId: "kx-unit6-stage-02",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。一個圓的圓周長是 50.24 公分，半徑是多少公分？答案只填數字。",
    answer: "8",
    hint: "先求直徑，再求半徑。",
    explanation: "50.24 ÷ 3.14＝16，直徑是 16 公分；16 ÷ 2＝8，所以半徑是 8 公分。",
    concept: "直徑與半徑：圓周長、直徑、半徑的轉換",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s03-q01",
    stageId: "kx-unit6-stage-03",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。半徑 7 公分的圓，圓周長是多少公分？答案只填數字。",
    answer: "43.96",
    hint: "先求直徑，再用直徑乘以 3.14。",
    explanation: "直徑＝7 × 2＝14 公分；圓周長＝3.14 × 14＝43.96 公分。",
    concept: "圓周長：由半徑求圓周長",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s03-q02",
    stageId: "kx-unit6-stage-03",
    unitId: "kx-unit6",
    type: "choice",
    prompt: "圓周率用 3.14。直徑 15 公分的圓，圓周長是多少公分？",
    answer: "47.1",
    hint: "圓周長＝圓周率×直徑。",
    explanation: "3.14 × 15＝47.1，所以圓周長是 47.1 公分。",
    concept: "圓周長：由直徑求圓周長",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["30", "37.68", "47.1", "94.2"],
  },
  {
    id: "static-u6-s03-q03",
    stageId: "kx-unit6-stage-03",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。直徑 6.4 公分的圓，圓周長是多少公分？答案只填數字。",
    answer: "20.096",
    hint: "小數直徑也一樣乘以圓周率。",
    explanation: "3.14 × 6.4＝20.096，所以圓周長是 20.096 公分。",
    concept: "圓周長：小數直徑的圓周長",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s03-q04",
    stageId: "kx-unit6-stage-03",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。一個直徑 70 公分的輪子轉 4 圈，前進多少公分？答案只填數字。",
    answer: "879.2",
    hint: "先求一圈的圓周長，再乘以 4。",
    explanation: "一圈長度＝3.14 × 70＝219.8 公分；4 圈前進 219.8 × 4＝879.2 公分。",
    concept: "圓周長：輪子轉動距離",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s03-q05",
    stageId: "kx-unit6-stage-03",
    unitId: "kx-unit6",
    type: "choice",
    prompt: "圓周率用 3.14。甲圓半徑 5 公分，乙圓直徑 12 公分，哪一個圓的圓周長比較長？",
    answer: "乙圓",
    hint: "把兩個圓都換成直徑後再求圓周長。",
    explanation: "甲圓直徑 10 公分，圓周長 31.4 公分；乙圓直徑 12 公分，圓周長 37.68 公分，所以乙圓較長。",
    concept: "圓周長：比較不同圓的圓周長",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["甲圓", "乙圓", "兩個一樣長", "資料不足"],
  },
  {
    id: "static-u6-s04-q01",
    stageId: "kx-unit6-stage-04",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。半徑 10 公分、圓心角 90 度的扇形，弧長是多少公分？答案只填數字。",
    answer: "15.7",
    hint: "90 度是整個圓的四分之一。",
    explanation: "整個圓的圓周長＝3.14 × 20＝62.8 公分；90 度是 1/4 圓，弧長＝62.8 ÷ 4＝15.7 公分。",
    concept: "扇形弧長：四分之一圓的弧長",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s04-q02",
    stageId: "kx-unit6-stage-04",
    unitId: "kx-unit6",
    type: "choice",
    prompt: "圓周率用 3.14。直徑 24 公分、圓心角 60 度的扇形，弧長是多少公分？",
    answer: "12.56",
    hint: "60 度是 360 度的六分之一。",
    explanation: "整個圓的圓周長＝3.14 × 24＝75.36 公分；弧長＝75.36 ÷ 6＝12.56 公分。",
    concept: "扇形弧長：六分之一圓的弧長",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["6.28", "12.56", "25.12", "75.36"],
  },
  {
    id: "static-u6-s04-q03",
    stageId: "kx-unit6-stage-04",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。半徑 9 公分、圓心角 120 度的扇形，弧長是多少公分？答案只填數字。",
    answer: "18.84",
    hint: "120 度是 360 度的三分之一。",
    explanation: "整個圓的圓周長＝3.14 × 18＝56.52 公分；弧長＝56.52 ÷ 3＝18.84 公分。",
    concept: "扇形弧長：三分之一圓的弧長",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s04-q04",
    stageId: "kx-unit6-stage-04",
    unitId: "kx-unit6",
    type: "choice",
    prompt: "圓周率用 3.14。半徑 6 公分、圓心角 270 度的扇形，弧長是多少公分？",
    answer: "28.26",
    hint: "270 度是整個圓的四分之三。",
    explanation: "整個圓的圓周長＝3.14 × 12＝37.68 公分；弧長＝37.68 × 3/4＝28.26 公分。",
    concept: "扇形弧長：四分之三圓的弧長",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["9.42", "18.84", "28.26", "37.68"],
  },
  {
    id: "static-u6-s04-q05",
    stageId: "kx-unit6-stage-04",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。直徑 18 公分的半圓，弧長是多少公分？答案只填數字。",
    answer: "28.26",
    hint: "半圓弧長是整個圓周長的一半。",
    explanation: "整個圓的圓周長＝3.14 × 18＝56.52 公分；半圓弧長＝56.52 ÷ 2＝28.26 公分。",
    concept: "扇形弧長：半圓弧長",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s05-q01",
    stageId: "kx-unit6-stage-05",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。半徑 10 公分、圓心角 90 度的扇形，周長是多少公分？答案只填數字。",
    answer: "35.7",
    hint: "扇形周長＝弧長＋兩條半徑。",
    explanation: "弧長＝3.14 × 20 ÷ 4＝15.7 公分；扇形周長＝15.7＋10＋10＝35.7 公分。",
    concept: "扇形周長：弧長加兩條半徑",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s05-q02",
    stageId: "kx-unit6-stage-05",
    unitId: "kx-unit6",
    type: "choice",
    prompt: "圓周率用 3.14。直徑 20 公分的半圓形鐵片，周長是多少公分？",
    answer: "51.4",
    hint: "半圓周長包含半圓弧長和一條直徑。",
    explanation: "半圓弧長＝3.14 × 20 ÷ 2＝31.4 公分；周長＝31.4＋20＝51.4 公分。",
    concept: "扇形周長：半圓周長",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["31.4", "40", "51.4", "62.8"],
  },
  {
    id: "static-u6-s05-q03",
    stageId: "kx-unit6-stage-05",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。半徑 21 公分、圓心角 60 度的扇形，周長是多少公分？答案只填數字。",
    answer: "63.98",
    hint: "60 度弧長是整個圓周長的六分之一。",
    explanation: "整個圓周長＝3.14 × 42＝131.88 公分；弧長＝131.88 ÷ 6＝21.98 公分；周長＝21.98＋21＋21＝63.98 公分。",
    concept: "扇形周長：六分之一圓扇形",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s05-q04",
    stageId: "kx-unit6-stage-05",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。半徑 12 公分、圓心角 120 度的扇形，周長是多少公分？答案只填數字。",
    answer: "49.12",
    hint: "先求三分之一圓的弧長，再加兩條半徑。",
    explanation: "整個圓周長＝3.14 × 24＝75.36 公分；弧長＝75.36 ÷ 3＝25.12 公分；周長＝25.12＋12＋12＝49.12 公分。",
    concept: "扇形周長：三分之一圓扇形",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s05-q05",
    stageId: "kx-unit6-stage-05",
    unitId: "kx-unit6",
    type: "choice",
    prompt: "圓周率用 3.14。直徑 14 公分、圓心角 90 度的扇形，周長是多少公分？",
    answer: "24.99",
    hint: "先求四分之一圓的弧長，再加兩條半徑。",
    explanation: "整個圓周長＝3.14 × 14＝43.96 公分；弧長＝43.96 ÷ 4＝10.99 公分；半徑是 7 公分，周長＝10.99＋7＋7＝24.99 公分。",
    concept: "扇形周長：已知直徑求扇形周長",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["17.99", "24.99", "38.96", "43.96"],
  },
  {
    id: "static-u6-s06-q01",
    stageId: "kx-unit6-stage-06",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。一個圓的圓周長是 31.4 公分，半徑是多少公分？答案只填數字。",
    answer: "5",
    hint: "先用圓周長除以 3.14 求直徑。",
    explanation: "31.4 ÷ 3.14＝10，直徑是 10 公分；10 ÷ 2＝5，所以半徑是 5 公分。",
    concept: "反推半徑：由圓周長求半徑",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s06-q02",
    stageId: "kx-unit6-stage-06",
    unitId: "kx-unit6",
    type: "choice",
    prompt: "圓周率用 3.14。一個圓的圓周長是 125.6 公分，半徑是多少公分？",
    answer: "20",
    hint: "圓周長除以圓周率可得到直徑。",
    explanation: "125.6 ÷ 3.14＝40，直徑是 40 公分；40 ÷ 2＝20，所以半徑是 20 公分。",
    concept: "反推半徑：較大圓的半徑",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["10", "20", "40", "62.8"],
  },
  {
    id: "static-u6-s06-q03",
    stageId: "kx-unit6-stage-06",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。一個 90 度扇形的弧長是 31.4 公分，這個扇形的半徑是多少公分？答案只填數字。",
    answer: "20",
    hint: "90 度弧長是整個圓周長的四分之一。",
    explanation: "整個圓周長＝31.4 × 4＝125.6 公分；直徑＝125.6 ÷ 3.14＝40 公分；半徑＝40 ÷ 2＝20 公分。",
    concept: "反推半徑：由扇形弧長求半徑",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s06-q04",
    stageId: "kx-unit6-stage-06",
    unitId: "kx-unit6",
    type: "choice",
    prompt: "圓周率用 3.14。一個 90 度扇形的周長是 35.7 公分，半徑是多少公分？",
    answer: "10",
    hint: "扇形周長包含四分之一圓弧長和兩條半徑。",
    explanation: "若半徑是 10 公分，直徑是 20 公分，90 度弧長＝3.14 × 20 ÷ 4＝15.7 公分；周長＝15.7＋10＋10＝35.7 公分，所以半徑是 10 公分。",
    concept: "反推半徑：由扇形周長判斷半徑",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["5", "8", "10", "12"],
  },
  {
    id: "static-u6-s06-q05",
    stageId: "kx-unit6-stage-06",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。一個 120 度扇形的弧長是 18.84 公分，半徑是多少公分？答案只填數字。",
    answer: "9",
    hint: "120 度弧長是整個圓周長的三分之一。",
    explanation: "整個圓周長＝18.84 × 3＝56.52 公分；直徑＝56.52 ÷ 3.14＝18 公分；半徑＝18 ÷ 2＝9 公分。",
    concept: "反推半徑：由三分之一圓弧長求半徑",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s07-q01",
    stageId: "kx-unit6-stage-07",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。操場中央有一個直徑 50 公尺的圓形跑道，跑一圈是幾公尺？答案只填數字。",
    answer: "157",
    hint: "跑一圈就是圓周長。",
    explanation: "圓周長＝3.14 × 50＝157，所以跑一圈是 157 公尺。",
    concept: "生活應用：圓形跑道周長",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s07-q02",
    stageId: "kx-unit6-stage-07",
    unitId: "kx-unit6",
    type: "choice",
    prompt: "圓周率用 3.14。半徑 3 公尺的圓形花圃外圍要圍一圈繩子，至少需要幾公尺？",
    answer: "18.84",
    hint: "繩長至少等於花圃的圓周長。",
    explanation: "直徑＝3 × 2＝6 公尺；圓周長＝3.14 × 6＝18.84 公尺。",
    concept: "生活應用：圓形花圃圍繩",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["9.42", "18.84", "28.26", "37.68"],
  },
  {
    id: "static-u6-s07-q03",
    stageId: "kx-unit6-stage-07",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。電風扇圓形護網的半徑是 20 公分，外框一圈長多少公分？答案只填數字。",
    answer: "125.6",
    hint: "外框一圈就是半徑 20 公分圓的圓周長。",
    explanation: "直徑＝20 × 2＝40 公分；圓周長＝3.14 × 40＝125.6 公分。",
    concept: "生活應用：圓形護網外框",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s07-q04",
    stageId: "kx-unit6-stage-07",
    unitId: "kx-unit6",
    type: "input",
    prompt: "圓周率用 3.14。直徑 0.6 公尺的輪子轉 100 圈，前進多少公尺？答案只填數字。",
    answer: "188.4",
    hint: "先求一圈前進距離，再乘以 100。",
    explanation: "一圈長度＝3.14 × 0.6＝1.884 公尺；100 圈前進 1.884 × 100＝188.4 公尺。",
    concept: "生活應用：輪子滾動距離",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u6-s07-q05",
    stageId: "kx-unit6-stage-07",
    unitId: "kx-unit6",
    type: "choice",
    prompt: "圓周率用 3.14。一片半徑 4 公尺、圓心角 90 度的扇形窗框，需要包住弧邊和兩條半徑，總長是多少公尺？",
    answer: "14.28",
    hint: "這是扇形周長，不只算弧長。",
    explanation: "90 度弧長＝3.14 × 8 ÷ 4＝6.28 公尺；總長＝6.28＋4＋4＝14.28 公尺。",
    concept: "生活應用：扇形窗框周長",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["6.28", "10.28", "14.28", "25.12"],
  },
  {
    id: "static-u7-s01-q01",
    stageId: "kx-unit7-stage-01",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。半徑 10 公分的圓，面積是多少平方公分？答案只填數字。",
    answer: "314",
    hint: "圓面積＝圓周率×半徑×半徑。",
    explanation: "圓面積＝3.14 × 10 × 10＝314，所以面積是 314 平方公分。",
    concept: "圓面積：由半徑求面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s01-q02",
    stageId: "kx-unit7-stage-01",
    unitId: "kx-unit7",
    type: "choice",
    prompt: "圓周率用 3.14。直徑 12 公分的圓，面積是多少平方公分？",
    answer: "113.04",
    hint: "先把直徑除以 2 得到半徑。",
    explanation: "半徑＝12 ÷ 2＝6 公分；面積＝3.14 × 6 × 6＝113.04 平方公分。",
    concept: "圓面積：由直徑求面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["37.68", "75.36", "113.04", "452.16"],
  },
  {
    id: "static-u7-s01-q03",
    stageId: "kx-unit7-stage-01",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。半徑 7 公分的圓，面積是多少平方公分？答案只填數字。",
    answer: "153.86",
    hint: "先算 7×7，再乘以 3.14。",
    explanation: "7 × 7＝49；3.14 × 49＝153.86，所以面積是 153.86 平方公分。",
    concept: "圓面積：半徑平方乘以圓周率",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s01-q04",
    stageId: "kx-unit7-stage-01",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。半徑 2.5 公分的圓，面積是多少平方公分？答案只填數字。",
    answer: "19.625",
    hint: "小數半徑也要先乘自己一次。",
    explanation: "2.5 × 2.5＝6.25；3.14 × 6.25＝19.625，所以面積是 19.625 平方公分。",
    concept: "圓面積：小數半徑的圓面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s01-q05",
    stageId: "kx-unit7-stage-01",
    unitId: "kx-unit7",
    type: "choice",
    prompt: "圓周率用 3.14。半徑 8 公分的圓，面積是多少平方公分？",
    answer: "200.96",
    hint: "半徑平方是 64。",
    explanation: "8 × 8＝64；3.14 × 64＝200.96，所以面積是 200.96 平方公分。",
    concept: "圓面積：選擇正確面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["50.24", "100.48", "200.96", "401.92"],
  },
  {
    id: "static-u7-s02-q01",
    stageId: "kx-unit7-stage-02",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。半徑 9 公分的圓，半徑平方是多少？答案只填數字。",
    answer: "81",
    hint: "半徑平方就是半徑乘以自己。",
    explanation: "9 × 9＝81，所以半徑平方是 81；求面積時會再乘以 3.14。",
    concept: "半徑平方：理解 r×r",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s02-q02",
    stageId: "kx-unit7-stage-02",
    unitId: "kx-unit7",
    type: "choice",
    prompt: "圓周率用 3.14。如果一個圓的半徑平方是 49，圓面積是多少平方公分？",
    answer: "153.86",
    hint: "圓面積＝3.14×半徑平方。",
    explanation: "3.14 × 49＝153.86，所以圓面積是 153.86 平方公分。",
    concept: "半徑平方：用 r² 求圓面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["49", "98", "153.86", "307.72"],
  },
  {
    id: "static-u7-s02-q03",
    stageId: "kx-unit7-stage-02",
    unitId: "kx-unit7",
    type: "input",
    prompt: "直徑 14 公分的圓，半徑平方是多少？答案只填數字。",
    answer: "49",
    hint: "先把直徑除以 2 得到半徑。",
    explanation: "半徑＝14 ÷ 2＝7 公分；半徑平方＝7 × 7＝49。",
    concept: "半徑平方：由直徑求 r²",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s02-q04",
    stageId: "kx-unit7-stage-02",
    unitId: "kx-unit7",
    type: "choice",
    prompt: "哪一個半徑的圓，半徑平方是 64？單位都是公分。",
    answer: "8 公分",
    hint: "找哪個數乘以自己等於 64。",
    explanation: "8 × 8＝64，所以半徑是 8 公分時，半徑平方是 64。",
    concept: "半徑平方：由 r² 判斷半徑",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["4 公分", "6 公分", "8 公分", "16 公分"],
  },
  {
    id: "static-u7-s02-q05",
    stageId: "kx-unit7-stage-02",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。一個圓的面積是 78.5 平方公分，半徑平方是多少？答案只填數字。",
    answer: "25",
    hint: "用圓面積除以 3.14。",
    explanation: "78.5 ÷ 3.14＝25，所以半徑平方是 25。",
    concept: "半徑平方：由圓面積反推 r²",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s03-q01",
    stageId: "kx-unit7-stage-03",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。半徑 10 公分、圓心角 90 度的扇形，面積是多少平方公分？答案只填數字。",
    answer: "78.5",
    hint: "90 度是整個圓面積的四分之一。",
    explanation: "整個圓面積＝3.14 × 10 × 10＝314 平方公分；扇形面積＝314 ÷ 4＝78.5 平方公分。",
    concept: "扇形面積：四分之一圓面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s03-q02",
    stageId: "kx-unit7-stage-03",
    unitId: "kx-unit7",
    type: "choice",
    prompt: "圓周率用 3.14。半徑 12 公分、圓心角 60 度的扇形，面積是多少平方公分？",
    answer: "75.36",
    hint: "60 度是 360 度的六分之一。",
    explanation: "整個圓面積＝3.14 × 12 × 12＝452.16 平方公分；扇形面積＝452.16 ÷ 6＝75.36 平方公分。",
    concept: "扇形面積：六分之一圓面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["37.68", "75.36", "150.72", "452.16"],
  },
  {
    id: "static-u7-s03-q03",
    stageId: "kx-unit7-stage-03",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。半徑 6 公分、圓心角 120 度的扇形，面積是多少平方公分？答案只填數字。",
    answer: "37.68",
    hint: "120 度是整個圓面積的三分之一。",
    explanation: "整個圓面積＝3.14 × 6 × 6＝113.04 平方公分；扇形面積＝113.04 ÷ 3＝37.68 平方公分。",
    concept: "扇形面積：三分之一圓面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s03-q04",
    stageId: "kx-unit7-stage-03",
    unitId: "kx-unit7",
    type: "choice",
    prompt: "圓周率用 3.14。直徑 20 公分、圓心角 72 度的扇形，面積是多少平方公分？",
    answer: "62.8",
    hint: "72 度是 360 度的五分之一，且半徑是 10 公分。",
    explanation: "整個圓面積＝3.14 × 10 × 10＝314 平方公分；扇形面積＝314 ÷ 5＝62.8 平方公分。",
    concept: "扇形面積：五分之一圓面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["31.4", "62.8", "125.6", "314"],
  },
  {
    id: "static-u7-s03-q05",
    stageId: "kx-unit7-stage-03",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。半徑 8 公分、圓心角 270 度的扇形，面積是多少平方公分？答案只填數字。",
    answer: "150.72",
    hint: "270 度是整個圓面積的四分之三。",
    explanation: "整個圓面積＝3.14 × 8 × 8＝200.96 平方公分；扇形面積＝200.96 × 3/4＝150.72 平方公分。",
    concept: "扇形面積：四分之三圓面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s04-q01",
    stageId: "kx-unit7-stage-04",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。半徑 10 公分的半圓，面積是多少平方公分？答案只填數字。",
    answer: "157",
    hint: "半圓面積是整個圓面積的一半。",
    explanation: "整個圓面積＝3.14 × 10 × 10＝314 平方公分；半圓面積＝314 ÷ 2＝157 平方公分。",
    concept: "半圓面積：整圓面積的一半",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s04-q02",
    stageId: "kx-unit7-stage-04",
    unitId: "kx-unit7",
    type: "choice",
    prompt: "圓周率用 3.14。直徑 16 公分的半圓，面積是多少平方公分？",
    answer: "100.48",
    hint: "先求半徑，再求整圓面積的一半。",
    explanation: "半徑＝16 ÷ 2＝8 公分；整圓面積＝3.14 × 8 × 8＝200.96 平方公分；半圓面積＝100.48 平方公分。",
    concept: "半圓面積：由直徑求半圓面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["50.24", "100.48", "200.96", "401.92"],
  },
  {
    id: "static-u7-s04-q03",
    stageId: "kx-unit7-stage-04",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。半徑 7 公分的半圓，面積是多少平方公分？答案只填數字。",
    answer: "76.93",
    hint: "先求半徑 7 公分的整圓面積。",
    explanation: "整圓面積＝3.14 × 7 × 7＝153.86 平方公分；半圓面積＝153.86 ÷ 2＝76.93 平方公分。",
    concept: "半圓面積：半徑 7 公分的半圓",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s04-q04",
    stageId: "kx-unit7-stage-04",
    unitId: "kx-unit7",
    type: "choice",
    prompt: "圓周率用 3.14。半徑 12 公分的半圓，面積是多少平方公分？",
    answer: "226.08",
    hint: "半徑平方是 144，先求整圓面積。",
    explanation: "整圓面積＝3.14 × 12 × 12＝452.16 平方公分；半圓面積＝452.16 ÷ 2＝226.08 平方公分。",
    concept: "半圓面積：選擇正確半圓面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["75.36", "150.72", "226.08", "452.16"],
  },
  {
    id: "static-u7-s04-q05",
    stageId: "kx-unit7-stage-04",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。直徑 12 公分的半圓，面積是多少平方公分？答案只填數字。",
    answer: "56.52",
    hint: "直徑 12 公分，所以半徑是 6 公分。",
    explanation: "半徑＝12 ÷ 2＝6 公分；整圓面積＝3.14 × 6 × 6＝113.04 平方公分；半圓面積＝113.04 ÷ 2＝56.52 平方公分。",
    concept: "半圓面積：直徑 12 公分的半圓",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s05-q01",
    stageId: "kx-unit7-stage-05",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。一個圓的面積是 314 平方公分，半徑是多少公分？答案只填數字。",
    answer: "10",
    hint: "先用面積除以 3.14，得到半徑平方。",
    explanation: "314 ÷ 3.14＝100，所以半徑平方是 100；10 × 10＝100，因此半徑是 10 公分。",
    concept: "反推半徑：由圓面積求半徑",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s05-q02",
    stageId: "kx-unit7-stage-05",
    unitId: "kx-unit7",
    type: "choice",
    prompt: "圓周率用 3.14。一個圓的面積是 78.5 平方公分，半徑是多少公分？",
    answer: "5",
    hint: "先反推半徑平方，再找平方數。",
    explanation: "78.5 ÷ 3.14＝25，所以半徑平方是 25；5 × 5＝25，因此半徑是 5 公分。",
    concept: "反推半徑：由較小圓面積求半徑",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["4", "5", "10", "25"],
  },
  {
    id: "static-u7-s05-q03",
    stageId: "kx-unit7-stage-05",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。一個半圓的面積是 157 平方公分，原來整個圓的半徑是多少公分？答案只填數字。",
    answer: "10",
    hint: "半圓面積先乘以 2，得到整圓面積。",
    explanation: "整圓面積＝157 × 2＝314 平方公分；314 ÷ 3.14＝100，所以半徑平方是 100，半徑是 10 公分。",
    concept: "反推半徑：由半圓面積求半徑",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s05-q04",
    stageId: "kx-unit7-stage-05",
    unitId: "kx-unit7",
    type: "choice",
    prompt: "圓周率用 3.14。一個 90 度扇形面積是 28.26 平方公分，原來整個圓的半徑是多少公分？",
    answer: "6",
    hint: "90 度扇形是整圓面積的四分之一。",
    explanation: "整圓面積＝28.26 × 4＝113.04 平方公分；113.04 ÷ 3.14＝36，所以半徑平方是 36，半徑是 6 公分。",
    concept: "反推半徑：由扇形面積求半徑",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["3", "6", "9", "12"],
  },
  {
    id: "static-u7-s05-q05",
    stageId: "kx-unit7-stage-05",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。一個圓的面積是 200.96 平方公分，半徑是多少公分？答案只填數字。",
    answer: "8",
    hint: "把面積除以圓周率後，找哪個數的平方相同。",
    explanation: "200.96 ÷ 3.14＝64，所以半徑平方是 64；8 × 8＝64，因此半徑是 8 公分。",
    concept: "反推半徑：由面積 200.96 反推",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s06-q01",
    stageId: "kx-unit7-stage-06",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。一個外圓半徑 10 公分、內圓半徑 4 公分的圓環，面積是多少平方公分？答案只填數字。",
    answer: "263.76",
    hint: "圓環面積＝外圓面積－內圓面積。",
    explanation: "外圓面積＝3.14 × 10 × 10＝314 平方公分；內圓面積＝3.14 × 4 × 4＝50.24 平方公分；圓環面積＝314－50.24＝263.76 平方公分。",
    concept: "組合圖形：圓環面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s06-q02",
    stageId: "kx-unit7-stage-06",
    unitId: "kx-unit7",
    type: "choice",
    prompt: "圓周率用 3.14。一個長 20 公分、寬 10 公分的長方形，左右各接一個半徑 5 公分的半圓，組合圖形面積是多少平方公分？",
    answer: "278.5",
    hint: "兩個半圓合起來是一個完整的圓。",
    explanation: "長方形面積＝20 × 10＝200 平方公分；兩個半圓合成半徑 5 公分的圓，面積＝3.14 × 5 × 5＝78.5 平方公分；總面積＝200＋78.5＝278.5 平方公分。",
    concept: "組合圖形：長方形加兩個半圓",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["200", "239.25", "278.5", "357"],
  },
  {
    id: "static-u7-s06-q03",
    stageId: "kx-unit7-stage-06",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。邊長 14 公分的正方形內畫一個直徑 14 公分的圓，正方形扣掉圓後的面積是多少平方公分？答案只填數字。",
    answer: "42.14",
    hint: "用正方形面積減去圓面積。",
    explanation: "正方形面積＝14 × 14＝196 平方公分；圓半徑＝7 公分，圓面積＝3.14 × 7 × 7＝153.86 平方公分；剩下面積＝196－153.86＝42.14 平方公分。",
    concept: "組合圖形：正方形扣圓",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s06-q04",
    stageId: "kx-unit7-stage-06",
    unitId: "kx-unit7",
    type: "choice",
    prompt: "圓周率用 3.14。兩個半徑 6 公分的四分之一圓合在一起，面積是多少平方公分？",
    answer: "56.52",
    hint: "兩個四分之一圓合起來是半圓。",
    explanation: "半徑 6 公分的整圓面積＝3.14 × 6 × 6＝113.04 平方公分；兩個四分之一圓是半圓，面積＝113.04 ÷ 2＝56.52 平方公分。",
    concept: "組合圖形：兩個四分之一圓",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["28.26", "56.52", "84.78", "113.04"],
  },
  {
    id: "static-u7-s06-q05",
    stageId: "kx-unit7-stage-06",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。一個半徑 8 公分的半圓下方接一個底 16 公分、高 6 公分的三角形，組合圖形面積是多少平方公分？答案只填數字。",
    answer: "148.48",
    hint: "總面積＝半圓面積＋三角形面積。",
    explanation: "半圓面積＝3.14 × 8 × 8 ÷ 2＝100.48 平方公分；三角形面積＝16 × 6 ÷ 2＝48 平方公分；總面積＝100.48＋48＝148.48 平方公分。",
    concept: "組合圖形：半圓加三角形",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s07-q01",
    stageId: "kx-unit7-stage-07",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。一張圓桌的半徑是 0.5 公尺，桌面面積是多少平方公尺？答案只填數字。",
    answer: "0.785",
    hint: "用半徑 0.5 公尺乘以自己，再乘以 3.14。",
    explanation: "0.5 × 0.5＝0.25；3.14 × 0.25＝0.785，所以桌面面積是 0.785 平方公尺。",
    concept: "生活應用：圓桌面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s07-q02",
    stageId: "kx-unit7-stage-07",
    unitId: "kx-unit7",
    type: "choice",
    prompt: "圓周率用 3.14。一個披薩直徑 30 公分，面積是多少平方公分？",
    answer: "706.5",
    hint: "先求半徑 15 公分，再算圓面積。",
    explanation: "半徑＝30 ÷ 2＝15 公分；面積＝3.14 × 15 × 15＝706.5 平方公分。",
    concept: "生活應用：披薩面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["94.2", "225", "706.5", "2826"],
  },
  {
    id: "static-u7-s07-q03",
    stageId: "kx-unit7-stage-07",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。灑水器可灑到半徑 6 公尺、圓心角 90 度的扇形區域，面積是多少平方公尺？答案只填數字。",
    answer: "28.26",
    hint: "灑水範圍是四分之一圓。",
    explanation: "整個圓面積＝3.14 × 6 × 6＝113.04 平方公尺；90 度扇形面積＝113.04 ÷ 4＝28.26 平方公尺。",
    concept: "生活應用：扇形灑水面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s07-q04",
    stageId: "kx-unit7-stage-07",
    unitId: "kx-unit7",
    type: "input",
    prompt: "圓周率用 3.14。圓形池塘半徑 5 公尺，外圍鋪一圈寬 1 公尺的步道，步道面積是多少平方公尺？答案只填數字。",
    answer: "34.54",
    hint: "步道是外圓半徑 6 公尺與內圓半徑 5 公尺的圓環。",
    explanation: "外圓面積＝3.14 × 6 × 6＝113.04 平方公尺；池塘面積＝3.14 × 5 × 5＝78.5 平方公尺；步道面積＝113.04－78.5＝34.54 平方公尺。",
    concept: "生活應用：圓形步道面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
  },
  {
    id: "static-u7-s07-q05",
    stageId: "kx-unit7-stage-07",
    unitId: "kx-unit7",
    type: "choice",
    prompt: "圓周率用 3.14。舞台燈照亮半徑 15 公尺、圓心角 120 度的扇形區域，照亮面積是多少平方公尺？",
    answer: "235.5",
    hint: "120 度是整個圓面積的三分之一。",
    explanation: "整個圓面積＝3.14 × 15 × 15＝706.5 平方公尺；120 度扇形面積＝706.5 ÷ 3＝235.5 平方公尺。",
    concept: "生活應用：扇形照明面積",
    sourceMetadata: {
      source: "expert-authored-static-bank",
      reviewStatus: "approved",
      reviewer: "content-review",
    },
    choices: ["117.75", "235.5", "353.25", "706.5"],
  },
];
