// 康軒六上第 1～3 單元人工審訂靜態題庫。
export const STATIC_QUESTIONS_UNIT_1_3 = [
  {
    id: "kx-unit1-stage-01-q01", stageId: "kx-unit1-stage-01", unitId: "kx-unit1", type: "input",
    prompt: "29 的所有正因數共有幾個？請填入因數的個數。", answer: "2",
    hint: "因數要能整除 29，可從 1 開始逐一檢查。", explanation: "29 只有 1 和 29 兩個正因數，所以共有 2 個因數。",
    concept: "質數與合數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-01-q02", stageId: "kx-unit1-stage-01", unitId: "kx-unit1", type: "choice",
    prompt: "下列哪一個數是合數？", choices: ["17", "19", "21", "23"], answer: "21",
    hint: "找找看哪個數除了 1 和自己，還能被其他整數整除。", explanation: "21＝3×7，有 1 和自己以外的因數，因此 21 是合數；其餘三數都是質數。",
    concept: "質數與合數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-01-q03", stageId: "kx-unit1-stage-01", unitId: "kx-unit1", type: "input",
    prompt: "把 51 分類為質數或合數，請只填「質數」或「合數」。", answer: "合數",
    hint: "檢查 51 的各位數字和是否為 3 的倍數。", explanation: "5＋1＝6，51 可被 3 整除，且 51＝3×17，所以 51 是合數。",
    concept: "質數與合數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-01-q04", stageId: "kx-unit1-stage-01", unitId: "kx-unit1", type: "choice",
    prompt: "「2 是最小的質數，也是唯一的偶質數。」這個命題正確嗎？", choices: ["正確", "不正確"], answer: "正確",
    hint: "依照質數恰有兩個正因數的定義，分別檢查 2 與其他偶數。", explanation: "2 的正因數只有 1、2；大於 2 的偶數都可被 2 整除，因此命題正確。",
    concept: "質數與合數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-01-q05", stageId: "kx-unit1-stage-01", unitId: "kx-unit1", type: "input",
    prompt: "用 24 塊相同的正方形磁磚排成長、寬都是整數的長方形；把旋轉後相同的排法視為同一種，共有幾種排法？", answer: "4",
    hint: "把 24 的因數兩兩配對，且不重複計算長寬互換。", explanation: "因數配對為 1×24、2×12、3×8、4×6，共 4 種不同排法。",
    concept: "質數與合數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-02-q01", stageId: "kx-unit1-stage-02", unitId: "kx-unit1", type: "input",
    prompt: "將 84 做質因數分解後，質因數 2 的指數是多少？", answer: "2",
    hint: "連續用 2 除，直到商不能再被 2 整除。", explanation: "84＝2×42＝2×2×21＝2²×3×7，所以質因數 2 的指數是 2。",
    concept: "質因數分解", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-02-q02", stageId: "kx-unit1-stage-02", unitId: "kx-unit1", type: "choice",
    prompt: "下列哪一個是 180 的正確質因數分解？", choices: ["2×3²×5", "2²×3²×5", "2²×3×5²", "2×3×5²"], answer: "2²×3²×5",
    hint: "可先把 180 分成 18×10，再分解各因數。", explanation: "180＝18×10＝(2×3²)×(2×5)＝2²×3²×5。",
    concept: "質因數分解", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-02-q03", stageId: "kx-unit1-stage-02", unitId: "kx-unit1", type: "input",
    prompt: "某數的質因數分解是 2³×3×5，這個數是多少？", answer: "120",
    hint: "先算 2³，再依序乘上其餘質因數。", explanation: "2³×3×5＝8×3×5＝120。",
    concept: "質因數分解", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-02-q04", stageId: "kx-unit1-stage-02", unitId: "kx-unit1", type: "choice",
    prompt: "72＝2³×3²。下列哪一個數不是 72 的質因數？", choices: ["2", "3", "5", "2 和 3"], answer: "5",
    hint: "質因數必須是質數，且會出現在該數的質因數分解中。", explanation: "72 的質因數只有 2 和 3，5 沒有出現在分解式中，所以 5 不是 72 的質因數。",
    concept: "質因數分解", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-02-q05", stageId: "kx-unit1-stage-02", unitId: "kx-unit1", type: "input",
    prompt: "90 乘以一個正整數後會成為完全平方數；符合條件的最小正整數是多少？", answer: "10",
    hint: "先分解 90，完全平方數的每個質因數指數都要是偶數。", explanation: "90＝2×3²×5，需再乘 2×5＝10，得到 900＝2²×3²×5²。",
    concept: "質因數分解", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-03-q01", stageId: "kx-unit1-stage-03", unitId: "kx-unit1", type: "input",
    prompt: "18 和 24 的公因數共有幾個？", answer: "4",
    hint: "先分別列出兩數的因數，再找重複的數。", explanation: "18 和 24 的公因數是 1、2、3、6，共 4 個。",
    concept: "公因數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-03-q02", stageId: "kx-unit1-stage-03", unitId: "kx-unit1", type: "choice",
    prompt: "下列哪一個數同時是 42 和 70 的因數？", choices: ["6", "7", "10", "14"], answer: "7",
    hint: "分別用 42 和 70 除以每個選項，兩次都要整除。", explanation: "42÷7＝6，70÷7＝10，因此 7 是兩數的公因數；其他選項至少不能整除其中一數。",
    concept: "公因數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-03-q03", stageId: "kx-unit1-stage-03", unitId: "kx-unit1", type: "input",
    prompt: "老師把 30 枝鉛筆和 45 塊橡皮擦平均分成若干份，每份的鉛筆數與橡皮擦數都相同且沒有剩餘。若分成 5 份，每份共有幾件文具？", answer: "15",
    hint: "先確認 5 能同時整除兩種文具數，再算每份兩種數量的和。", explanation: "每份有 30÷5＝6 枝鉛筆、45÷5＝9 塊橡皮擦，共 6＋9＝15 件。",
    concept: "公因數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-03-q04", stageId: "kx-unit1-stage-03", unitId: "kx-unit1", type: "choice",
    prompt: "「只要一個數能整除 36，它就一定是 36 和 48 的公因數。」這個命題正確嗎？", choices: ["正確", "不正確"], answer: "不正確",
    hint: "公因數必須同時整除兩個數，可找一個只整除 36 的例子。", explanation: "例如 9 能整除 36，卻不能整除 48，所以命題不正確。",
    concept: "公因數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-03-q05", stageId: "kx-unit1-stage-03", unitId: "kx-unit1", type: "input",
    prompt: "20 和 30 的所有公因數相加，總和是多少？", answer: "18",
    hint: "先找出兩數共同的因數，再把它們相加。", explanation: "20 和 30 的公因數是 1、2、5、10，總和為 1＋2＋5＋10＝18。",
    concept: "公因數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-04-q01", stageId: "kx-unit1-stage-04", unitId: "kx-unit1", type: "input",
    prompt: "求 48 和 72 的最大公因數。", answer: "24",
    hint: "可用短除法，連續除以兩數共同的質因數。", explanation: "48＝2⁴×3，72＝2³×3²，共同部分是 2³×3＝24。",
    concept: "最大公因數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-04-q02", stageId: "kx-unit1-stage-04", unitId: "kx-unit1", type: "choice",
    prompt: "哪一組數的最大公因數是 6？", choices: ["14 和 21", "18 和 24", "24 和 36", "30 和 45"], answer: "18 和 24",
    hint: "分別找出每組的共同質因數，注意要取最大的公因數。", explanation: "18 和 24 的最大公因數是 6；其餘三組的最大公因數依序為 7、12、15。",
    concept: "最大公因數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-04-q03", stageId: "kx-unit1-stage-04", unitId: "kx-unit1", type: "input",
    prompt: "兩個數的最大公因數是 8，其中一個數是 24，另一個數是 40。24 和 40 各除以 8 後，兩個商的和是多少？", answer: "8",
    hint: "依序把兩數除以已知的最大公因數。", explanation: "24÷8＝3，40÷8＝5，兩個商的和是 3＋5＝8。",
    concept: "最大公因數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-04-q04", stageId: "kx-unit1-stage-04", unitId: "kx-unit1", type: "choice",
    prompt: "有 36 顆紅球和 60 顆藍球，要裝成內容完全相同且全部用完的禮物袋。最多可裝幾袋？", choices: ["6", "12", "18", "24"], answer: "12",
    hint: "袋數必須同時整除兩種球的數量，而且要取最大值。", explanation: "36 和 60 的最大公因數是 12，所以最多裝 12 袋，每袋有 3 顆紅球和 5 顆藍球。",
    concept: "最大公因數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-04-q05", stageId: "kx-unit1-stage-04", unitId: "kx-unit1", type: "input",
    prompt: "一張長 84 公分、寬 60 公分的長方形紙，要裁成邊長為整數公分且一樣大的最大正方形，不可剩紙。每個正方形的邊長是多少公分？", answer: "12",
    hint: "最大正方形的邊長要同時整除長與寬。", explanation: "84 和 60 的最大公因數是 12，因此最大正方形的邊長是 12 公分。",
    concept: "最大公因數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-05-q01", stageId: "kx-unit1-stage-05", unitId: "kx-unit1", type: "input",
    prompt: "在 1 到 50 的正整數中，6 和 8 的公倍數共有幾個？", answer: "2",
    hint: "先找 6 和 8 的最小公倍數，再依序列出不超過 50 的倍數。", explanation: "6 和 8 的最小公倍數是 24；不超過 50 的公倍數為 24、48，共 2 個。",
    concept: "公倍數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-05-q02", stageId: "kx-unit1-stage-05", unitId: "kx-unit1", type: "choice",
    prompt: "下列哪一個數同時是 9 和 12 的倍數？", choices: ["18", "24", "36", "48"], answer: "36",
    hint: "把每個選項分別除以 9 和 12，兩次都要沒有餘數。", explanation: "36÷9＝4，36÷12＝3，所以 36 是兩數的公倍數；其他選項無法同時被 9、12 整除。",
    concept: "公倍數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-05-q03", stageId: "kx-unit1-stage-05", unitId: "kx-unit1", type: "input",
    prompt: "已知 40 和 60 都是 10 與某正整數的公倍數，且此正整數大於 10。符合條件的最小正整數是多少？", answer: "20",
    hint: "這個數必須同時是 40 和 60 的因數，並且大於 10。", explanation: "40 和 60 的公因數中，大於 10 的最小值是 20；40、60 也都是 10 和 20 的倍數。",
    concept: "公倍數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-05-q04", stageId: "kx-unit1-stage-05", unitId: "kx-unit1", type: "choice",
    prompt: "「兩個正整數的公倍數有無限多個。」這個命題正確嗎？", choices: ["正確", "不正確"], answer: "正確",
    hint: "找到一個公倍數後，想想它的 2 倍、3 倍是否仍是公倍數。", explanation: "任一公倍數的正整數倍仍是公倍數，因此兩個正整數的公倍數有無限多個。",
    concept: "公倍數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-05-q05", stageId: "kx-unit1-stage-05", unitId: "kx-unit1", type: "input",
    prompt: "小華每 4 天游泳一次、每 6 天跑步一次。今天兩項都做，從今天的隔天起算，30 天內有幾天會再次同一天做兩項運動？", answer: "2",
    hint: "共同進行的日期間隔是 4 和 6 的公倍數，列出不超過 30 的日期。", explanation: "4 和 6 的公倍數在 30 以內為 12、24，所以有 2 天會同時做兩項運動。",
    concept: "公倍數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-06-q01", stageId: "kx-unit1-stage-06", unitId: "kx-unit1", type: "input",
    prompt: "求 18 和 24 的最小公倍數。", answer: "72",
    hint: "用質因數分解時，各質因數取兩數中較大的指數。", explanation: "18＝2×3²，24＝2³×3，最小公倍數是 2³×3²＝72。",
    concept: "最小公倍數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-06-q02", stageId: "kx-unit1-stage-06", unitId: "kx-unit1", type: "choice",
    prompt: "下列哪一組數的最小公倍數是 30？", choices: ["4 和 6", "5 和 6", "8 和 10", "12 和 15"], answer: "5 和 6",
    hint: "分別求各組的最小公倍數。",
    explanation: "5 和 6 互質，最小公倍數為 5×6＝30；其餘三組的最小公倍數依序為 12、40、60。",
    concept: "最小公倍數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-06-q03", stageId: "kx-unit1-stage-06", unitId: "kx-unit1", type: "input",
    prompt: "某正整數是 8 和 12 的公倍數，且介於 50 與 80 之間。這個數是多少？", answer: "72",
    hint: "先求最小公倍數，再列出落在指定範圍內的倍數。", explanation: "8 和 12 的最小公倍數是 24；24 的倍數中，只有 72 介於 50 與 80 之間。",
    concept: "最小公倍數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-06-q04", stageId: "kx-unit1-stage-06", unitId: "kx-unit1", type: "choice",
    prompt: "甲燈每 15 秒閃一次，乙燈每 20 秒閃一次，現在同時閃亮。至少再過幾秒會再次同時閃亮？", choices: ["30 秒", "45 秒", "60 秒", "300 秒"], answer: "60 秒",
    hint: "再次同時閃亮的最短時間是兩個間隔的最小公倍數。", explanation: "15＝3×5，20＝2²×5，最小公倍數為 2²×3×5＝60，所以 60 秒後再次同時閃亮。",
    concept: "最小公倍數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-06-q05", stageId: "kx-unit1-stage-06", unitId: "kx-unit1", type: "input",
    prompt: "一批糖果若每 12 顆裝一盒或每 18 顆裝一盒，都能剛好裝完。已知糖果超過 100 顆且少於 150 顆，這批糖果有幾顆？", answer: "108",
    hint: "先求 12 和 18 的最小公倍數，再找指定範圍內的倍數。", explanation: "12 和 18 的最小公倍數是 36；36 的倍數中，只有 108 介於 100 與 150 之間。",
    concept: "最小公倍數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-07-q01", stageId: "kx-unit1-stage-07", unitId: "kx-unit1", type: "input",
    prompt: "用短除法求 36 和 54 的最大公因數，答案是多少？", answer: "18",
    hint: "兩數可共同除以 2，再共同除以 3、3。", explanation: "36、54 共同短除以 2、3、3，左側共同除數乘積為 2×3×3＝18。",
    concept: "短除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-07-q02", stageId: "kx-unit1-stage-07", unitId: "kx-unit1", type: "choice",
    prompt: "用短除法計算 20 和 30 的最小公倍數時，共同短除以 2、5 後，最後兩個互質的商是哪一組？", choices: ["1 和 1", "2 和 3", "4 和 6", "10 和 15"], answer: "2 和 3",
    hint: "依序把 20、30 同時除以 2，再同時除以 5。", explanation: "20、30 同除以 2 得 10、15，再同除以 5 得 2、3，所以最後的商是 2 和 3。",
    concept: "短除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-07-q03", stageId: "kx-unit1-stage-07", unitId: "kx-unit1", type: "input",
    prompt: "以短除法處理 24、36、60，三數先共同除以 2，再共同除以 2。此時三個商的總和是多少？", answer: "30",
    hint: "每次都把三個數一起除以左側的共同除數。", explanation: "第一次得到 12、18、30，第二次得到 6、9、15，總和為 6＋9＋15＝30。",
    concept: "短除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-07-q04", stageId: "kx-unit1-stage-07", unitId: "kx-unit1", type: "choice",
    prompt: "用短除法求兩數的最小公倍數時，應把哪些數相乘？", choices: ["只乘所有共同除數", "只乘最後兩個商", "共同除數與最後所有商都相乘", "把原來兩數直接相加"], answer: "共同除數與最後所有商都相乘",
    hint: "最小公倍數要包含兩個原數所需的全部質因數。", explanation: "短除法求最小公倍數，要將左側的所有共同除數和最後剩下的各商全部相乘。",
    concept: "短除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-07-q05", stageId: "kx-unit1-stage-07", unitId: "kx-unit1", type: "input",
    prompt: "用短除法求 42 和 70 的最大公因數與最小公倍數，兩個結果相加是多少？", answer: "224",
    hint: "兩數可共同除以 2、7；最大公因數乘上最後兩商可得最小公倍數。", explanation: "共同除數乘積為 2×7＝14；最後商為 3、5，最小公倍數為 14×3×5＝210；相加得 224。",
    concept: "短除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-08-q01", stageId: "kx-unit1-stage-08", unitId: "kx-unit1", type: "input",
    prompt: "園遊會有 48 瓶果汁和 64 個麵包，要分成內容相同且全部用完的最多份餐點。最多可分成幾份？", answer: "16",
    hint: "份數要同時整除兩種物品數量，並且要最大。", explanation: "48 和 64 的最大公因數是 16，所以最多分成 16 份。",
    concept: "生活應用", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-08-q02", stageId: "kx-unit1-stage-08", unitId: "kx-unit1", type: "choice",
    prompt: "公車甲每 12 分鐘一班，公車乙每 18 分鐘一班，上午 8:00 同時發車。下一次同時發車是幾點？", choices: ["8:24", "8:30", "8:36", "8:54"], answer: "8:36",
    hint: "先求兩個發車間隔的最小公倍數，再加到 8:00。", explanation: "12 和 18 的最小公倍數是 36，所以下一次同時發車是 8:36。",
    concept: "生活應用", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-08-q03", stageId: "kx-unit1-stage-08", unitId: "kx-unit1", type: "input",
    prompt: "長 96 公分、寬 72 公分的長方形看板，要用邊長相同且為整數公分的最大正方形貼紙鋪滿。共需要幾張貼紙？", answer: "12",
    hint: "先用最大公因數求貼紙邊長，再計算長邊與寬邊各排幾張。", explanation: "96 和 72 的最大公因數是 24；長邊排 4 張、寬邊排 3 張，共 4×3＝12 張。",
    concept: "生活應用", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-08-q04", stageId: "kx-unit1-stage-08", unitId: "kx-unit1", type: "choice",
    prompt: "有一批雞蛋，6 個一盒或 8 個一盒都剛好裝完。下列哪個數量可能是這批雞蛋的數量？", choices: ["36", "40", "48", "54"], answer: "48",
    hint: "雞蛋數必須同時是 6 和 8 的倍數。", explanation: "48÷6＝8 且 48÷8＝6，所以 48 同時是 6 和 8 的倍數。",
    concept: "生活應用", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit1-stage-08-q05", stageId: "kx-unit1-stage-08", unitId: "kx-unit1", type: "input",
    prompt: "運動場一圈長 300 公尺。小安每 4 分鐘跑一圈，小美每 6 分鐘跑一圈，兩人同時從起點出發。第一次同時回到起點時，小安共跑了幾公尺？", answer: "900",
    hint: "先求兩人同時回到起點所需的最短時間，再算小安跑了幾圈。", explanation: "4 和 6 的最小公倍數是 12 分鐘；小安跑 12÷4＝3 圈，共 300×3＝900 公尺。",
    concept: "生活應用", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-01-q01", stageId: "kx-unit2-stage-01", unitId: "kx-unit2", type: "input",
    prompt: "7/9 的倒數是多少？請用最簡分數 a/b 作答。", answer: "9/7",
    hint: "倒數會交換原分數的分子與分母。", explanation: "7/9 的分子、分母交換後是 9/7，且 7/9×9/7＝1。",
    concept: "倒數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-01-q02", stageId: "kx-unit2-stage-01", unitId: "kx-unit2", type: "choice",
    prompt: "下列哪一組數互為倒數？", choices: ["3/5 和 5/3", "2/7 和 2/7", "4/9 和 9/5", "6 和 1/5"], answer: "3/5 和 5/3",
    hint: "互為倒數的兩數相乘會等於 1。", explanation: "3/5×5/3＝1，所以 3/5 和 5/3 互為倒數；其餘各組乘積都不等於 1。",
    concept: "倒數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-01-q03", stageId: "kx-unit2-stage-01", unitId: "kx-unit2", type: "input",
    prompt: "帶分數 2又1/3 的倒數是多少？請用最簡分數 a/b 作答。", answer: "3/7",
    hint: "先把帶分數化成假分數，再交換分子與分母。", explanation: "2又1/3＝7/3，交換分子與分母得到倒數 3/7。",
    concept: "倒數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-01-q04", stageId: "kx-unit2-stage-01", unitId: "kx-unit2", type: "choice",
    prompt: "「0 有倒數，0 的倒數仍是 0。」這個命題正確嗎？", choices: ["正確", "不正確"], answer: "不正確",
    hint: "倒數必須能與原數相乘得到 1。", explanation: "0 乘以任何數都等於 0，不可能等於 1，所以 0 沒有倒數，命題不正確。",
    concept: "倒數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-01-q05", stageId: "kx-unit2-stage-01", unitId: "kx-unit2", type: "input",
    prompt: "某正數和 5/8 的乘積是 1，這個正數是多少？請用最簡分數 a/b 作答。", answer: "8/5",
    hint: "乘積為 1 的兩個非零數互為倒數。", explanation: "5/8 的倒數是 8/5，而 5/8×8/5＝1，所以這個正數是 8/5。",
    concept: "倒數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-02-q01", stageId: "kx-unit2-stage-02", unitId: "kx-unit2", type: "input",
    prompt: "計算 6÷3/4，請填整數答案。", answer: "8",
    hint: "除以一個非零分數，等於乘以它的倒數。", explanation: "6÷3/4＝6×4/3＝8。",
    concept: "整數除以分數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-02-q02", stageId: "kx-unit2-stage-02", unitId: "kx-unit2", type: "choice",
    prompt: "下列哪一個算式與 5÷2/3 的值相等？", choices: ["5×2/3", "5×3/2", "2/3×1/5", "5－2/3"], answer: "5×3/2",
    hint: "把除數改成它的倒數，同時把除法改成乘法。", explanation: "除以 2/3 等於乘以其倒數 3/2，所以 5÷2/3＝5×3/2。",
    concept: "整數除以分數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-02-q03", stageId: "kx-unit2-stage-02", unitId: "kx-unit2", type: "input",
    prompt: "一條長 8 公尺的繩子，每 2/5 公尺剪一段，全部剪完可得到幾段？", answer: "20",
    hint: "用繩子總長除以每段長度。", explanation: "8÷2/5＝8×5/2＝20，所以可得到 20 段。",
    concept: "整數除以分數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-02-q04", stageId: "kx-unit2-stage-02", unitId: "kx-unit2", type: "choice",
    prompt: "若正整數 4 除以一個小於 1 的正分數，所得的商和 4 相比如何？", choices: ["一定大於 4", "一定等於 4", "一定小於 4", "可能是 0"], answer: "一定大於 4",
    hint: "除以小於 1 的正數，可以想成每一小份能裝幾份。", explanation: "小於 1 的正分數，其倒數大於 1；4 乘以大於 1 的數，結果一定大於 4。",
    concept: "整數除以分數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-02-q05", stageId: "kx-unit2-stage-02", unitId: "kx-unit2", type: "input",
    prompt: "某個正分數除數使 9÷此分數＝12。這個除數是多少？請用最簡分數 a/b 作答。", answer: "3/4",
    hint: "由被除數÷除數＝商，可用被除數÷商求除數。", explanation: "除數＝9÷12＝9/12＝3/4；檢查 9÷3/4＝12。",
    concept: "整數除以分數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-03-q01", stageId: "kx-unit2-stage-03", unitId: "kx-unit2", type: "input",
    prompt: "計算 5/6÷4，請用最簡分數 a/b 作答。", answer: "5/24",
    hint: "除以 4 等於乘以 1/4。", explanation: "5/6÷4＝5/6×1/4＝5/24。",
    concept: "分數除以整數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-03-q02", stageId: "kx-unit2-stage-03", unitId: "kx-unit2", type: "choice",
    prompt: "把 3/5 公升果汁平均倒入 3 個杯子，每杯有多少公升？", choices: ["1/5 公升", "3/8 公升", "3/5 公升", "9/5 公升"], answer: "1/5 公升",
    hint: "總量平均分成 3 份，要用總量除以 3。", explanation: "3/5÷3＝3/5×1/3＝1/5，所以每杯有 1/5 公升。",
    concept: "分數除以整數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-03-q03", stageId: "kx-unit2-stage-03", unitId: "kx-unit2", type: "input",
    prompt: "7/8÷某正整數＝7/40，這個正整數是多少？", answer: "5",
    hint: "比較兩個分數的分母變化，或用被除數除以商。", explanation: "7/8÷5＝7/8×1/5＝7/40，所以這個正整數是 5。",
    concept: "分數除以整數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-03-q04", stageId: "kx-unit2-stage-03", unitId: "kx-unit2", type: "choice",
    prompt: "「一個正分數除以大於 1 的整數，商一定比原正分數小。」這個命題正確嗎？", choices: ["正確", "不正確"], answer: "正確",
    hint: "除以大於 1 的整數，等於乘以一個小於 1 的正分數。", explanation: "除以整數 n（n＞1）等於乘以 1/n，而 0＜1/n＜1，所以商一定比原正分數小。",
    concept: "分數除以整數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-03-q05", stageId: "kx-unit2-stage-03", unitId: "kx-unit2", type: "input",
    prompt: "一塊 9/10 公斤的黏土平均分給 6 人，每人分得多少公斤？請用最簡分數 a/b 作答。", answer: "3/20",
    hint: "用黏土總重量除以人數，最後記得約分。", explanation: "9/10÷6＝9/60＝3/20，所以每人分得 3/20 公斤。",
    concept: "分數除以整數", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-04-q01", stageId: "kx-unit2-stage-04", unitId: "kx-unit2", type: "input",
    prompt: "計算 7/12÷5/12，請用最簡分數 a/b 作答。", answer: "7/5",
    hint: "同分母分數相除時，公分母可以約去。", explanation: "7/12÷5/12＝7/12×12/5＝7/5。",
    concept: "同分母分數除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-04-q02", stageId: "kx-unit2-stage-04", unitId: "kx-unit2", type: "choice",
    prompt: "一桶有 9/10 公升的水，每杯裝 3/10 公升，可以裝滿幾杯？", choices: ["2 杯", "3 杯", "6 杯", "27 杯"], answer: "3 杯",
    hint: "兩個量的單位相同，用總量除以每杯容量。", explanation: "9/10÷3/10＝9÷3＝3，所以可以裝滿 3 杯。",
    concept: "同分母分數除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-04-q03", stageId: "kx-unit2-stage-04", unitId: "kx-unit2", type: "input",
    prompt: "某分數除以 2/9 的商是 3，且某分數與除數同分母。某分數是多少？請用最簡分數 a/b 作答。", answer: "2/3",
    hint: "被除數＝商×除數。", explanation: "某分數＝3×2/9＝6/9＝2/3；原式可寫成 6/9÷2/9＝3。",
    concept: "同分母分數除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-04-q04", stageId: "kx-unit2-stage-04", unitId: "kx-unit2", type: "choice",
    prompt: "比較 4/11÷7/11 與 1，下列敘述何者正確？", choices: ["商大於 1", "商等於 1", "商小於 1", "無法比較"], answer: "商小於 1",
    hint: "同分母時，可比較被除數與除數的分子大小。", explanation: "4/11＜7/11，正數除以比自己大的正數，商小於 1；實際商為 4/7。",
    concept: "同分母分數除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-04-q05", stageId: "kx-unit2-stage-04", unitId: "kx-unit2", type: "input",
    prompt: "一條緞帶長 11/12 公尺，每 2/12 公尺剪一段。最多可剪出幾段完整的緞帶？", answer: "5",
    hint: "先算可分成多少份；題目只問完整段數，剩餘不足一段不計。", explanation: "11/12÷2/12＝11/2＝5又1/2，所以最多剪出 5 段完整緞帶。",
    concept: "同分母分數除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-05-q01", stageId: "kx-unit2-stage-05", unitId: "kx-unit2", type: "input",
    prompt: "計算 3/4÷5/6，請用最簡分數 a/b 作答。", answer: "9/10",
    hint: "除以 5/6 等於乘以 6/5，乘之前可先約分。", explanation: "3/4÷5/6＝3/4×6/5＝18/20＝9/10。",
    concept: "異分母分數除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-05-q02", stageId: "kx-unit2-stage-05", unitId: "kx-unit2", type: "choice",
    prompt: "下列哪一個算式的商等於 2？", choices: ["2/3÷1/3", "2/3÷3/4", "1/2÷2/3", "3/5÷5/6"], answer: "2/3÷1/3",
    hint: "逐一把除法改成乘以倒數，再約分。", explanation: "2/3÷1/3＝2；其餘三式的商分別為 8/9、3/4、18/25。",
    concept: "異分母分數除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-05-q03", stageId: "kx-unit2-stage-05", unitId: "kx-unit2", type: "input",
    prompt: "5/8÷某正分數＝3/2，這個正分數是多少？請用最簡分數 a/b 作答。", answer: "5/12",
    hint: "除數＝被除數÷商。", explanation: "除數＝5/8÷3/2＝5/8×2/3＝10/24＝5/12。",
    concept: "異分母分數除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-05-q04", stageId: "kx-unit2-stage-05", unitId: "kx-unit2", type: "choice",
    prompt: "「計算 4/5÷2/3 時，可以先將 4/5 和 2/3 通分，再把兩個新分子相除。」這個命題正確嗎？", choices: ["正確", "不正確"], answer: "正確",
    hint: "把兩分數都改寫成分母 15 的等值分數，檢查結果。", explanation: "4/5＝12/15、2/3＝10/15，因此 12/15÷10/15＝12÷10＝6/5，與乘倒數的結果相同。",
    concept: "異分母分數除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-05-q05", stageId: "kx-unit2-stage-05", unitId: "kx-unit2", type: "input",
    prompt: "製作一個模型需要 7/12 公尺鐵絲。現有 7/2 公尺鐵絲，最多可製作幾個完整模型？", answer: "6",
    hint: "用鐵絲總長除以每個模型所需長度。", explanation: "7/2÷7/12＝7/2×12/7＝6，因此可製作 6 個完整模型。",
    concept: "異分母分數除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-06-q01", stageId: "kx-unit2-stage-06", unitId: "kx-unit2", type: "input",
    prompt: "計算 2又1/4÷1又1/2，請用最簡分數 a/b 作答。", answer: "3/2",
    hint: "先把兩個帶分數都化成假分數，再乘以除數的倒數。", explanation: "2又1/4＝9/4，1又1/2＝3/2；9/4÷3/2＝9/4×2/3＝3/2。",
    concept: "帶分數除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-06-q02", stageId: "kx-unit2-stage-06", unitId: "kx-unit2", type: "choice",
    prompt: "3又1/3÷2又2/3 的商是多少？", choices: ["4/5", "5/4", "8/9", "6"], answer: "5/4",
    hint: "先化成 10/3 和 8/3，再計算。", explanation: "10/3÷8/3＝10/3×3/8＝10/8＝5/4。",
    concept: "帶分數除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-06-q03", stageId: "kx-unit2-stage-06", unitId: "kx-unit2", type: "input",
    prompt: "一桶油有 4又1/2 公升，每瓶裝 3/4 公升，全部裝完需要幾個瓶子？", answer: "6",
    hint: "先把總量化成假分數，再除以每瓶容量。", explanation: "4又1/2＝9/2；9/2÷3/4＝9/2×4/3＝6，所以需要 6 個瓶子。",
    concept: "帶分數除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-06-q04", stageId: "kx-unit2-stage-06", unitId: "kx-unit2", type: "choice",
    prompt: "計算帶分數除法時，第一個必要步驟通常是什麼？", choices: ["都化成假分數", "分子分母同時加 1", "只交換被除數的分子分母", "先把整數部分相除"], answer: "都化成假分數",
    hint: "帶分數必須先改寫成方便進行乘除的分數形式。", explanation: "先將帶分數化為假分數，接著把除法改成乘以除數的倒數，才能正確運算。",
    concept: "帶分數除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-06-q05", stageId: "kx-unit2-stage-06", unitId: "kx-unit2", type: "input",
    prompt: "某帶分數除以 1又1/4，商是 2。這個帶分數是多少？請以「a又b/c」格式作答。", answer: "2又1/2",
    hint: "被除數＝商×除數。", explanation: "2×1又1/4＝2×5/4＝10/4＝5/2＝2又1/2。",
    concept: "帶分數除法", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-07-q01", stageId: "kx-unit2-stage-07", unitId: "kx-unit2", type: "input",
    prompt: "3/4 公升果汁平均分給 6 人，每人分得多少公升？請用最簡分數 a/b 作答。", answer: "1/8",
    hint: "這是等分問題，用總量除以人數。", explanation: "3/4÷6＝3/24＝1/8，所以每人分得 1/8 公升。",
    concept: "商的意義", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-07-q02", stageId: "kx-unit2-stage-07", unitId: "kx-unit2", type: "choice",
    prompt: "算式 5/6÷1/12 最適合表示下列哪一個問題？", choices: ["5/6 裡有幾個 1/12", "把 1/12 平均分成 5/6 份", "5/6 與 1/12 的總和", "5/6 的 1/12 倍"], answer: "5/6 裡有幾個 1/12",
    hint: "除法可以表示一個量包含多少個指定的小量。", explanation: "5/6÷1/12 是求 5/6 中包含幾個 1/12，結果為 10。",
    concept: "商的意義", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-07-q03", stageId: "kx-unit2-stage-07", unitId: "kx-unit2", type: "input",
    prompt: "2/3 公斤糖可裝成 4 包一樣重的小包，每包重多少公斤？請用最簡分數 a/b 作答。", answer: "1/6",
    hint: "已知總量和份數，求每份量要用除法。", explanation: "2/3÷4＝2/12＝1/6，所以每包重 1/6 公斤。",
    concept: "商的意義", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-07-q04", stageId: "kx-unit2-stage-07", unitId: "kx-unit2", type: "choice",
    prompt: "有 3/2 公尺緞帶，每 1/4 公尺剪一段。算式 3/2÷1/4 所得的商 6 表示什麼？", choices: ["每段長 6 公尺", "可剪成 6 段", "還剩 6 公尺", "需要 6/4 公尺"], answer: "可剪成 6 段",
    hint: "商的單位由題目所問的數量決定。", explanation: "總長除以每段長度，得到可包含的段數，因此商 6 表示可剪成 6 段。",
    concept: "商的意義", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-07-q05", stageId: "kx-unit2-stage-07", unitId: "kx-unit2", type: "input",
    prompt: "一個長方形面積是 5/6 平方公尺，長是 5/3 公尺，寬是多少公尺？請用最簡分數 a/b 作答。", answer: "1/2",
    hint: "長方形面積÷長＝寬。", explanation: "5/6÷5/3＝5/6×3/5＝1/2，所以寬是 1/2 公尺。",
    concept: "商的意義", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-08-q01", stageId: "kx-unit2-stage-08", unitId: "kx-unit2", type: "input",
    prompt: "3/5 公斤米售價 54 元，1 公斤米售價多少元？", answer: "90",
    hint: "求單位量，用總價除以重量。", explanation: "54÷3/5＝54×5/3＝90，所以 1 公斤售價 90 元。",
    concept: "單位量", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-08-q02", stageId: "kx-unit2-stage-08", unitId: "kx-unit2", type: "choice",
    prompt: "甲跑 3/4 公里用 6 分鐘，平均每分鐘跑多少公里？", choices: ["1/8 公里", "3/8 公里", "9/2 公里", "8 公里"], answer: "1/8 公里",
    hint: "平均每分鐘的距離＝總距離÷時間。", explanation: "3/4÷6＝3/24＝1/8，所以平均每分鐘跑 1/8 公里。",
    concept: "單位量", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-08-q03", stageId: "kx-unit2-stage-08", unitId: "kx-unit2", type: "input",
    prompt: "一臺機器 2又1/2 小時生產 300 個零件，平均每小時生產幾個？", answer: "120",
    hint: "把 2又1/2 化成 5/2，再用總數量除以時間。", explanation: "300÷5/2＝300×2/5＝120，所以平均每小時生產 120 個。",
    concept: "單位量", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-08-q04", stageId: "kx-unit2-stage-08", unitId: "kx-unit2", type: "choice",
    prompt: "A 店 4/5 公斤蘋果賣 72 元，B 店 3/4 公斤同種蘋果賣 69 元。哪一家每公斤較便宜？", choices: ["A 店", "B 店", "兩店相同", "資料不足"], answer: "A 店",
    hint: "分別求兩家店 1 公斤的價格再比較。", explanation: "A 店每公斤 72÷4/5＝90 元；B 店每公斤 69÷3/4＝92 元，所以 A 店較便宜。",
    concept: "單位量", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-08-q05", stageId: "kx-unit2-stage-08", unitId: "kx-unit2", type: "input",
    prompt: "每公尺布售價 84 元，小芳付 210 元可買多少公尺？請用最簡分數 a/b 作答。", answer: "5/2",
    hint: "購買長度＝總價÷每公尺價格。", explanation: "210÷84＝210/84＝5/2，所以可買 5/2 公尺。",
    concept: "單位量", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-09-q01", stageId: "kx-unit2-stage-09", unitId: "kx-unit2", type: "input",
    prompt: "有 6 公升茶，每瓶裝 3/8 公升，全部裝完需要幾個瓶子？", answer: "16",
    hint: "瓶數＝總量÷每瓶容量。", explanation: "6÷3/8＝6×8/3＝16，所以需要 16 個瓶子。",
    concept: "生活應用", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-09-q02", stageId: "kx-unit2-stage-09", unitId: "kx-unit2", type: "choice",
    prompt: "一輛車用 3又1/2 公升汽油行駛 49 公里，平均每公升行駛多少公里？", choices: ["7 公里", "14 公里", "17.5 公里", "171.5 公里"], answer: "14 公里",
    hint: "用行駛距離除以汽油量。", explanation: "49÷3又1/2＝49÷7/2＝49×2/7＝14，所以平均每公升行駛 14 公里。",
    concept: "生活應用", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-09-q03", stageId: "kx-unit2-stage-09", unitId: "kx-unit2", type: "input",
    prompt: "一條步道長 2又2/5 公里，小安每小時走 4/5 公里，走完全程需要幾小時？", answer: "3",
    hint: "時間＝路程÷每小時行走距離。", explanation: "2又2/5＝12/5；12/5÷4/5＝12/4＝3，所以需要 3 小時。",
    concept: "生活應用", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-09-q04", stageId: "kx-unit2-stage-09", unitId: "kx-unit2", type: "choice",
    prompt: "做一個蛋糕需要 2/3 杯糖，現有 3又1/3 杯糖。若只做完整蛋糕，最多能做幾個？", choices: ["2 個", "4 個", "5 個", "6 個"], answer: "5 個",
    hint: "用糖的總量除以每個蛋糕需要的量。", explanation: "3又1/3＝10/3；10/3÷2/3＝5，所以最多能做 5 個完整蛋糕。",
    concept: "生活應用", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit2-stage-09-q05", stageId: "kx-unit2-stage-09", unitId: "kx-unit2", type: "input",
    prompt: "一塊面積 7又1/2 平方公尺的長方形菜圃，寬是 2又1/2 公尺，長是多少公尺？", answer: "3",
    hint: "長＝面積÷寬，先將帶分數化成假分數。", explanation: "7又1/2＝15/2，2又1/2＝5/2；15/2÷5/2＝3，所以長是 3 公尺。",
    concept: "生活應用", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-01-q01", stageId: "kx-unit3-stage-01", unitId: "kx-unit3", type: "input",
    prompt: "數列 5、9、13、17、……的下一項是多少？", answer: "21",
    hint: "比較相鄰兩項的差。", explanation: "每一項都比前一項多 4，所以 17＋4＝21。",
    concept: "數列規律", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-01-q02", stageId: "kx-unit3-stage-01", unitId: "kx-unit3", type: "choice",
    prompt: "數列 2、6、18、54、……是依照哪一個規律排列？", choices: ["每次加 4", "每次乘 2", "每次乘 3", "每次加前一項"], answer: "每次乘 3",
    hint: "檢查後一項是前一項的幾倍。", explanation: "2×3＝6、6×3＝18、18×3＝54，所以規律是每次乘 3。",
    concept: "數列規律", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-01-q03", stageId: "kx-unit3-stage-01", unitId: "kx-unit3", type: "input",
    prompt: "一個等差數列每次增加 7，第 5 項是 36，第 1 項是多少？", answer: "8",
    hint: "從第 5 項往前退 4 次，每次減 7。", explanation: "36－7×4＝36－28＝8，所以第 1 項是 8。",
    concept: "數列規律", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-01-q04", stageId: "kx-unit3-stage-01", unitId: "kx-unit3", type: "choice",
    prompt: "數列 1、4、2、5、3、6、……的第 7 項是多少？", choices: ["4", "6", "7", "8"], answer: "4",
    hint: "把奇數位置與偶數位置分開觀察。", explanation: "奇數位置依序是 1、2、3、4，偶數位置依序是 4、5、6；第 7 項在奇數位置，所以是 4。",
    concept: "數列規律", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-01-q05", stageId: "kx-unit3-stage-01", unitId: "kx-unit3", type: "input",
    prompt: "數列 3、6、9、12、15 的五個數相加，總和是多少？", answer: "45",
    hint: "可將第一項與末項、第二項與倒數第二項配對。", explanation: "3＋15＝18，6＋12＝18，再加中間的 9，總和為 45。",
    concept: "數列規律", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-02-q01", stageId: "kx-unit3-stage-02", unitId: "kx-unit3", type: "input",
    prompt: "用火柴棒排相連的正方形：1 個正方形用 4 根，2 個用 7 根，3 個用 10 根。排 6 個相連正方形需要幾根？", answer: "19",
    hint: "每增加一個正方形，會和前一個共用一邊。", explanation: "第一個用 4 根，之後每增加一個多 3 根；排 6 個需 4＋3×5＝19 根。",
    concept: "圖形規律", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-02-q02", stageId: "kx-unit3-stage-02", unitId: "kx-unit3", type: "choice",
    prompt: "用圓點排三角形，第 1 層有 1 點、第 2 層有 2 點、第 3 層有 3 點。排成 4 層三角形共有幾點？", choices: ["7 點", "8 點", "9 點", "10 點"], answer: "10 點",
    hint: "把每一層的點數相加。", explanation: "4 層的總點數為 1＋2＋3＋4＝10 點。",
    concept: "圖形規律", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-02-q03", stageId: "kx-unit3-stage-02", unitId: "kx-unit3", type: "input",
    prompt: "一串圖案依序重複「○、△、□」。第 20 個圖案是什麼？請填入符號。", answer: "△",
    hint: "每 3 個為一組，求 20 除以 3 的餘數。", explanation: "20÷3＝6 餘 2，餘 2 對應每組第 2 個圖案，所以是 △。",
    concept: "圖形規律", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-02-q04", stageId: "kx-unit3-stage-02", unitId: "kx-unit3", type: "choice",
    prompt: "正方形方陣第 1 圖有 1 個點、第 2 圖有 4 個點、第 3 圖有 9 個點。第 5 圖有幾個點？", choices: ["15 個", "20 個", "25 個", "30 個"], answer: "25 個",
    hint: "第幾圖的點會排成幾列、幾行。", explanation: "第 5 圖排成 5×5 的方陣，共有 25 個點。",
    concept: "圖形規律", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-02-q05", stageId: "kx-unit3-stage-02", unitId: "kx-unit3", type: "input",
    prompt: "階梯圖的方格數依序是 2、5、9、14、……，相鄰兩圖增加的方格數依序為 3、4、5。下一圖共有幾個方格？", answer: "20",
    hint: "下一次增加的數量會比 5 再多 1。", explanation: "增加量依序為 3、4、5、6，所以下一圖有 14＋6＝20 個方格。",
    concept: "圖形規律", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-03-q01", stageId: "kx-unit3-stage-03", unitId: "kx-unit3", type: "input",
    prompt: "甲、乙兩數的和是 86。甲數增加 9，為使兩數的和仍是 86，乙數要減少多少？", answer: "9",
    hint: "總和不變時，一個加多少，另一個就要有相反變化。", explanation: "甲增加 9，乙必須減少 9，兩項變化互相抵銷，總和才維持 86。",
    concept: "和不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-03-q02", stageId: "kx-unit3-stage-03", unitId: "kx-unit3", type: "choice",
    prompt: "哪一個算式運用了「和不變」的關係，將 398＋257 改成較容易計算的形式？", choices: ["400＋255", "400＋257", "398＋255", "390＋250"], answer: "400＋255",
    hint: "一個加 2 時，另一個要減 2。", explanation: "398 增加 2 成為 400，257 減少 2 成為 255，總和不變，且 400＋255＝655。",
    concept: "和不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-03-q03", stageId: "kx-unit3-stage-03", unitId: "kx-unit3", type: "input",
    prompt: "兩個數的和是 120，其中一個數從 47 變成 52；若和不變，另一個數變成多少？", answer: "68",
    hint: "先求原來另一個數，或直接觀察第一個數增加了多少。", explanation: "原來另一數為 120－47＝73；第一數增加 5，另一數減少 5，變成 68。",
    concept: "和不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-03-q04", stageId: "kx-unit3-stage-03", unitId: "kx-unit3", type: "choice",
    prompt: "「把加法算式中的兩個加數都增加 4，總和不變。」這個命題正確嗎？", choices: ["正確", "不正確"], answer: "不正確",
    hint: "分別計算兩個加數的變化對總和造成的影響。", explanation: "兩個加數各增加 4，總和會增加 4＋4＝8，因此命題不正確。",
    concept: "和不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-03-q05", stageId: "kx-unit3-stage-03", unitId: "kx-unit3", type: "input",
    prompt: "書架上層有 58 本書、下層有 42 本書。從上層移幾本到下層後，兩層本數會相同？", answer: "8",
    hint: "移動前後總本數不變；先求平均每層應有幾本。", explanation: "總共有 100 本，平均每層 50 本；上層需移出 58－50＝8 本。",
    concept: "和不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-04-q01", stageId: "kx-unit3-stage-04", unitId: "kx-unit3", type: "input",
    prompt: "92－37＝55。若被減數與減數都增加 8，新算式的差是多少？", answer: "55",
    hint: "被減數和減數同時增加相同的數，兩項變化會互相抵銷。", explanation: "(92＋8)－(37＋8)＝100－45＝55，差不變。",
    concept: "差不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-04-q02", stageId: "kx-unit3-stage-04", unitId: "kx-unit3", type: "choice",
    prompt: "計算 503－298 時，哪一個等值算式最方便？", choices: ["505－300", "503－300", "500－298", "505－298"], answer: "505－300",
    hint: "讓被減數與減數同時增加相同的數。", explanation: "兩數同時加 2，差不變；503－298＝505－300＝205。",
    concept: "差不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-04-q03", stageId: "kx-unit3-stage-04", unitId: "kx-unit3", type: "input",
    prompt: "甲比乙多 26。若甲、乙各減少 7，甲仍比乙多多少？", answer: "26",
    hint: "兩個量同時減少相同數量，觀察相差量是否改變。", explanation: "(甲－7)－(乙－7)＝甲－乙＝26，所以仍相差 26。",
    concept: "差不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-04-q04", stageId: "kx-unit3-stage-04", unitId: "kx-unit3", type: "choice",
    prompt: "「被減數增加 6，減數不變，差也增加 6。」這個命題正確嗎？", choices: ["正確", "不正確"], answer: "正確",
    hint: "可用一組簡單數字代入，觀察被減數單獨增加的影響。", explanation: "只有被減數增加 6 時，新的差＝原差＋6，所以命題正確。",
    concept: "差不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-04-q05", stageId: "kx-unit3-stage-04", unitId: "kx-unit3", type: "input",
    prompt: "爸爸今年 42 歲，女兒今年 12 歲。再過 15 年，爸爸比女兒大幾歲？", answer: "30",
    hint: "兩人的年齡會同時增加相同年數。", explanation: "現在相差 42－12＝30 歲；15 年後兩人都增加 15 歲，年齡差仍是 30 歲。",
    concept: "差不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-05-q01", stageId: "kx-unit3-stage-05", unitId: "kx-unit3", type: "input",
    prompt: "18×24＝432。若 18 乘以 2，為使積仍是 432，24 要除以多少？", answer: "2",
    hint: "一個因數放大幾倍，另一個因數要做相反的倍數變化。", explanation: "(18×2)×(24÷2)＝18×24＝432，所以 24 要除以 2。",
    concept: "積不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-05-q02", stageId: "kx-unit3-stage-05", unitId: "kx-unit3", type: "choice",
    prompt: "哪一個算式和 25×48 的積相等？", choices: ["50×24", "50×48", "25×24", "100×24"], answer: "50×24",
    hint: "一個因數乘 2，另一個因數要除以 2。", explanation: "25 乘 2 變 50，48 除以 2 變 24，因此 25×48＝50×24＝1200。",
    concept: "積不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-05-q03", stageId: "kx-unit3-stage-05", unitId: "kx-unit3", type: "input",
    prompt: "長方形面積是 96 平方公分。若長由 12 公分增加為 24 公分，面積不變時，寬是多少公分？", answer: "4",
    hint: "長變為原來的 2 倍，寬要變為原來的幾分之幾？", explanation: "原寬為 96÷12＝8 公分；長乘 2，寬除以 2，變為 4 公分。",
    concept: "積不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-05-q04", stageId: "kx-unit3-stage-05", unitId: "kx-unit3", type: "choice",
    prompt: "「兩個非零因數都乘以 3，乘積仍不變。」這個命題正確嗎？", choices: ["正確", "不正確"], answer: "不正確",
    hint: "分別考慮兩個乘 3 對乘積造成的倍數變化。", explanation: "兩個因數都乘 3，乘積會變為原來的 3×3＝9 倍，不會保持不變。",
    concept: "積不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-05-q05", stageId: "kx-unit3-stage-05", unitId: "kx-unit3", type: "input",
    prompt: "不用直式計算，利用積不變求 125×32 的值。", answer: "4000",
    hint: "可把 125 乘以 8，同時把 32 除以 8。", explanation: "125×32＝(125×8)×(32÷8)＝1000×4＝4000。",
    concept: "積不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-06-q01", stageId: "kx-unit3-stage-06", unitId: "kx-unit3", type: "input",
    prompt: "720÷90＝8。若被除數和除數同時除以 10，新的商是多少？", answer: "8",
    hint: "被除數與除數同時做相同的非零倍數變化，商不變。", explanation: "(720÷10)÷(90÷10)＝72÷9＝8。",
    concept: "商不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-06-q02", stageId: "kx-unit3-stage-06", unitId: "kx-unit3", type: "choice",
    prompt: "哪一個算式和 350÷14 的商相等？", choices: ["175÷7", "350÷7", "175÷14", "700÷14"], answer: "175÷7",
    hint: "被除數和除數要同時除以相同的非零數。", explanation: "350 和 14 同時除以 2，得到 175÷7，所以兩式的商相等，都是 25。",
    concept: "商不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-06-q03", stageId: "kx-unit3-stage-06", unitId: "kx-unit3", type: "input",
    prompt: "某除法算式的商是 12。被除數乘以 5，除數也乘以 5 後，商是多少？", answer: "12",
    hint: "兩者同時乘以相同的非零數，不改變兩者的倍數關係。", explanation: "(被除數×5)÷(除數×5)＝被除數÷除數，所以商仍為 12。",
    concept: "商不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-06-q04", stageId: "kx-unit3-stage-06", unitId: "kx-unit3", type: "choice",
    prompt: "「被除數乘以 4、除數乘以 2，商會變成原來的 2 倍。」這個命題正確嗎？", choices: ["正確", "不正確"], answer: "正確",
    hint: "比較被除數與除數各自的倍數變化。", explanation: "(被除數×4)÷(除數×2)＝原商×(4÷2)＝原商×2，所以命題正確。",
    concept: "商不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-06-q05", stageId: "kx-unit3-stage-06", unitId: "kx-unit3", type: "input",
    prompt: "利用商不變，把 4.8÷0.06 的被除數和除數同時乘以 100 後計算，商是多少？", answer: "80",
    hint: "同時乘以 100 可把除數化為整數。", explanation: "4.8÷0.06＝480÷6＝80。",
    concept: "商不變", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-07-q01", stageId: "kx-unit3-stage-07", unitId: "kx-unit3", type: "input",
    prompt: "在一條直線步道上，從起點到終點每隔 5 公尺設一盞燈，兩端都設燈。步道長 40 公尺，共設幾盞燈？", answer: "9",
    hint: "先求間隔數；直線兩端都設置時，盞數比間隔數多 1。", explanation: "40÷5＝8 個間隔，兩端都設燈共有 8＋1＝9 盞。",
    concept: "間隔問題", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-07-q02", stageId: "kx-unit3-stage-07", unitId: "kx-unit3", type: "choice",
    prompt: "一條繩子剪 6 次且每次只剪一處，最後共有幾段？", choices: ["5 段", "6 段", "7 段", "12 段"], answer: "7 段",
    hint: "每剪一次，段數會增加 1。", explanation: "未剪時有 1 段，剪 6 次增加 6 段，所以共有 1＋6＝7 段。",
    concept: "間隔問題", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-07-q03", stageId: "kx-unit3-stage-07", unitId: "kx-unit3", type: "input",
    prompt: "一條道路的一側從頭到尾共種 13 棵樹，相鄰兩樹距離都是 4 公尺。第一棵到最後一棵相距多少公尺？", answer: "48",
    hint: "13 棵樹之間有幾個間隔？", explanation: "13 棵樹形成 13－1＝12 個間隔，距離為 12×4＝48 公尺。",
    concept: "間隔問題", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-07-q04", stageId: "kx-unit3-stage-07", unitId: "kx-unit3", type: "choice",
    prompt: "在周長 60 公尺的圓形花圃外圍，每隔 5 公尺放一盆花，剛好繞一圈。需要幾盆花？", choices: ["11 盆", "12 盆", "13 盆", "15 盆"], answer: "12 盆",
    hint: "封閉圖形首尾相接，物件數和間隔數相同。", explanation: "60÷5＝12 個間隔；圓形首尾相接，不需再加 1，所以需要 12 盆。",
    concept: "間隔問題", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
  {
    id: "kx-unit3-stage-07-q05", stageId: "kx-unit3-stage-07", unitId: "kx-unit3", type: "input",
    prompt: "時鐘整點敲鐘，敲 6 下從第一下開始到最後一下共經過 10 秒。相鄰兩下的時間間隔是多少秒？", answer: "2",
    hint: "敲 6 下所形成的間隔數比敲擊次數少 1。", explanation: "6 下之間有 5 個時間間隔，10÷5＝2，所以相鄰兩下相隔 2 秒。",
    concept: "間隔問題", sourceMetadata: { source: "expert-authored-static-bank", reviewStatus: "approved", reviewer: "content-review" },
  },
];
